server {
    listen 80;
    listen [::]:80;
    server_name lumiere.mktk.cc dev-lumiere.mktk.cc;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name lumiere.mktk.cc;

    ssl_certificate /etc/letsencrypt/live/lumiere.mktk.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lumiere.mktk.cc/privkey.pem;

    location / {
        proxy_pass http://192.168.1.182:8083;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_read_timeout 120s;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name dev-lumiere.mktk.cc;

    ssl_certificate /etc/letsencrypt/live/lumiere.mktk.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lumiere.mktk.cc/privkey.pem;

    location / {
        proxy_pass http://192.168.1.182:8084;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_read_timeout 120s;
    }
}
